### ISSUE TITLE
DOC Add `Expr` background and supported expressions

### ISSUE THREAD

**Issue by lucyleeow** [pyapp-kit/app-model#106]
There is some great info in the `src/app_model/expressions/_expressions.py` module docstring, which is unfortunately not included in the documentation. Would you consider including this / is there a way to easily do this in the current documentation system?

Also would a list of supported comparisons / ops be useful?

**Comment by tlambert03** [comment]
sure, happy to have it included

**Comment by lucyleeow** [comment]
Would you just add to `docs/expressions.md` or is there a better way?

**Comment by tlambert03** [comment]
Let's move whatever you want from the module docstring  into the body of the Expr class docstring (which I think is already documented there), that way we can avoid duplication.
