### ISSUE TITLE
Should Kebindings.from_string fail on invalid/unkown keys ?

### ISSUE THREAD

**Issue by Carreau** [pyapp-kit/app-model#111]
* app-model version: latest

### Description

I was surprised by the following:

```
In [1]: str(KeyBinding.from_str('Meta+Shift+Return'))
Out[1]: 'Shift+Meta+'
```

A realized that `Return` is not a handled key, should we have a warning/error on invalid values ?

**Comment by tlambert03** [comment]
sure, seems like a good idea
