### ISSUE TITLE
Bug: exception during teardown of QModelMenu with submenus

### ISSUE THREAD

**Issue by tlambert03** [pyapp-kit/app-model#147]
Oh while you're here, I noticed that you can't build a `QModelMenu` for submenus because during teardown error results:

see: https://github.com/napari/napari/pull/4865/files#r1288031823

_Originally posted by @lucyleeow in https://github.com/pyapp-kit/app-model/issues/142#issuecomment-1792203460_
            
@lucyleeow, can you make a quick example of this bug?  I see the traceback you posted, but it's hard to determine exactly what you ran to get it.

**Comment by lucyleeow** [comment]
Sorry, I've been trying and failing to make a min reproducible example of the bug (I realise I don't understand it well).

In the mean time, in case you wanted to take a look, I re-created the original error in napari. Using [this branch](https://github.com/lucyleeow/napari/tree/test_qmenu) in my fork (just built a submenu `QModelMenu` in `_qt_main_window`), running the test: `napari/_qt/dialogs/_tests/test_reader_dialog.py::test_open_with_dialog_choices_persist`

**Comment by tlambert03** [comment]
thanks! that's sufficient.  Fix coming in #151

**Comment by lucyleeow** [comment]
Thanks, I was trying to reproduce by manually running `rebuild` on menu then submenu but I missed the event  where the menu was removed.

**Comment by tlambert03** [comment]
a quick tip there: the most useful information for an error that occurs during a callback connected to psygnal Signal will usually come one frame higher in the stack trace.  So, in your test error:

```python
napari/_qt/dialogs/_tests/test_reader_dialog.py .E                                                                                [0/1]
napari/_qt/dialogs/_tests/test_reader_dialog.py:170 test_open_with_dialog_choices_persist - psygnal._exceptions.EmitLoopErro…
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

>   ???

src/psygnal/_signal.py:990:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
src/psygnal/_weak_callback.py:377: in cb
    ???
../app-model/src/app_model/backends/qt/_qmenu.py:123: in _on_registry_changed
    self.rebuild()
../app-model/src/app_model/backends/qt/_qmenu.py:105: in rebuild
    _rebuild(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

menu = <app_model.backends.qt._qmenu.QModelMenu object at 0x13c44a7a0>, app = Application('test_app')
menu_id = <MenuId.FILE_SAMPLES: 'napari/file/samples'>, include_submenus = True, exclude = None

    def _rebuild(
        menu: QMenu | QToolBar,
        app: Application,
        menu_id: str,
        include_submenus: bool = True,
        exclude: Optional[Collection[str]] = None,
    ) -> None:
        """Rebuild menu by looking up `menu` in `Application`'s menu_registry."""
>       menu.clear()
E       RuntimeError: wrapped C/C++ object of type QModelMenu has been deleted

../app-model/src/app_model/backends/qt/_qmenu.py:314: RuntimeError

The above exception was the direct cause of the following exception:

_npe2pm = <npe2._pytest_plugin.TestPluginManager object at 0x13793d0f0>

    @pytest.fixture
    def builtins(_npe2pm: TestPluginManager):
>       with _npe2pm.tmp_plugin(package='napari') as plugin:

napari/conftest.py:287:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../miniforge3/envs/napari/lib/python3.10/site-packages/npe2/_dynamic_plugin.py:132: in __exit__
    self.cleanup()
../../../miniforge3/envs/napari/lib/python3.10/site-packages/npe2/_dynamic_plugin.py:90: in cleanup
    self.plugin_manager.unregister(self.manifest.name)
../../../miniforge3/envs/napari/lib/python3.10/site-packages/npe2/_plugin_manager.py:364: in unregister
    self.deactivate(key)
../../../miniforge3/envs/napari/lib/python3.10/site-packages/npe2/_plugin_manager.py:433: in deactivate
    ctx._dispose()
../../../miniforge3/envs/napari/lib/python3.10/site-packages/npe2/_plugin_manager.py:713: in _dispose
    self._disposables.pop()()
../app-model/src/app_model/registries/_menus_reg.py:71: in _dispose
    self.menus_changed.emit(changed_ids)
src/psygnal/_signal.py:945: in emit
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   psygnal._exceptions.EmitLoopError: calling <psygnal._weak_callback._WeakMethod object at 0x13c2c9ec0>
   with args=({<MenuId.FILE_SAMPLES: 'napari/file/samples'>},) caused RuntimeError:
   wrapped C/C++ object of type QModelMenu has been deleted.

src/psygnal/_signal.py:992: EmitLoopError
```

So, if you go one above "The above exception was the direct cause of the following exception: you'll see that the real error was in calling `menu.clear()` inside of the `_rebuild()` function, and that was called by `QModelMenu.rebuild` (line 105), and that in turn was called by `QModelMenu._on_registry_changed` (line 123).  That last bit is your key there.  Cause you can look to see what event is connected to `_on_registry_changed`, and there is only one: `self._app.menus.menus_changed.connect(self._on_registry_changed)` on line 64.

not like that's *super* clear :joy: ... but just a general tip to "look one higher" in the traceback :)

**Comment by lucyleeow** [comment]
Thanks! I guessed from the traceback that prior to the `_rebuild()` -> `menu.clear()`, the submenu had already been destroyed, I assume with the parent menu. I didn't work out what previous event caused the parent menu to be destroyed? 

I see `_on_registry_changed` loops through all `changed_ids` and runs `rebuild` and tried to run `rebuild` on parent menu then submenu but that did not work. Which makes sense as this wouldn't cause the parent menu to be destroyed before trying to `rebuild` the submenu. I saw the failure was during 'teardown' of the test so maybe the destroy was part of the clean up of `make_napari_viewer`? :confused:

**Comment by lucyleeow** [comment]
I can understand that once the parent menu is destroyed, a `menus_changed` event gets emitted? Which causes `rebuild` of the submeu. But I just didn't follow where the parent menu was destroyed?

**Comment by tlambert03** [comment]
> I didn't work out what previous event caused the parent menu to be destroyed?  I saw the failure was during 'teardown' of the test so maybe the destroy was part of the clean up of make_napari_viewer?

ah, yep! the thing that started it all off was the `with _npe2pm.tmp_plugin(package='napari') as plugin:` context manager.  When that context exits, it sets off a chain of cleanup:

```pytb
../../../miniforge3/envs/napari/lib/python3.10/site-packages/npe2/_dynamic_plugin.py:132: in __exit__
    self.cleanup()
../../../miniforge3/envs/napari/lib/python3.10/site-packages/npe2/_dynamic_plugin.py:90: in cleanup
    self.plugin_manager.unregister(self.manifest.name)
../../../miniforge3/envs/napari/lib/python3.10/site-packages/npe2/_plugin_manager.py:364: in unregister
    self.deactivate(key)
../../../miniforge3/envs/napari/lib/python3.10/site-packages/npe2/_plugin_manager.py:433: in deactivate
    ctx._dispose()
../../../miniforge3/envs/napari/lib/python3.10/site-packages/npe2/_plugin_manager.py:713: in _dispose
    self._disposables.pop()()
../app-model/src/app_model/registries/_menus_reg.py:71: in _dispose
    self.menus_changed.emit(changed_ids)
```

so, i guess you could say it all starts with npe2 `DynamicPlugin.__exit__`
https://github.com/napari/npe2/blob/main/src/npe2/_dynamic_plugin.py#L132

**Comment by lucyleeow** [comment]
Ahhh that makes sense. For parent menus, no `menus_changed` event is emitted because that menu has been removed from the registry but for parent menus with a submenu, the parent is removed from the registry but the submenu isn't (?) so `menus_changed` event is emitted with submenu as `changed_ids` ?

**Comment by lucyleeow** [comment]
Sorry, still confused about this. I can see that in `MenusRegistry` once all the menu items belonging to a key are removed, that key is deleted:

https://github.com/pyapp-kit/app-model/blob/0140de703687c8132feaaabc7d649ebf325dc5b3/src/app_model/registries/_menus_reg.py#L68-L70

But how would this result in deletion of the `QModelMenu` for the submenu?

The `DynamicPlugin.cleanup()` func and all follow on functions seem to be dealing with updating registries. I can't find where the `QModelMenu` for the submenu would be deleted?

Also I realise this would not be related to the parent menu ('napari/files' in this case) as removing a plugin is not going to result in that menu being deleted.

**Comment by tlambert03** [comment]
> I can't find where the QModelMenu for the submenu would be deleted

generally speaking, for *all* instances of `QObject` and any of it's subclasses (which is basically every object in Qt), as soon as the last pointer to the object gets garbage collected, Qt will delete the object.  So very often, you're not going to be looking for an explicit `delete` call anywhere, but rather figuring out why/where the last reference to the object got removed.

Here's a somewhat contrived example that you can run:

```python
from qtpy.QtWidgets import QApplication, QMainWindow, QPushButton

app = QApplication([])

window = QMainWindow()
btn1 = QPushButton("1")
btn2 = QPushButton("2")

# here window is assigned as the parent of btn1
window.setCentralWidget(btn1)
# because we can only have one central widget, btn1 is removed from window
# and Qt cleans up the memory for us
btn1.clicked.connect(lambda: window.setCentralWidget(btn2))
# but when we try to click on the new button, we have problem
# becuase our python pointer `btn1` now points to a deleted object
btn2.clicked.connect(lambda: window.setCentralWidget(btn1))

window.show()
app.exec()
```

on the second button click, you'll get:

```pytb
Traceback (most recent call last):
  File "/Users/talley/dev/self/app-model/x.py", line 10, in <lambda>
    btn2.clicked.connect(lambda: window.setCentralWidget(btn1))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: wrapped C/C++ object of type QPushButton has been deleted
zsh: abort      python x.py
```

... so in this case, I would have to dig a bit deeper into the cleanup chain to tell you what race condition caused the `QModelMenu` to be deleted before that final callback was received.  It's definitely not in the bit of code you linked there in the registries (nothing outside of the qt module would result in a qt object getting deleted like this...), but that bit of code *is* getting called after the Qt object was deleted (somewhere else) and that's the problem.  not sure where that somewhere else is.  I am curious and will try to find it, but it's also not terribly unusual to just catch the runtime error and be done with it :)

**Comment by tlambert03** [comment]
one more thing worth mentioning here... 
there is a line that was designed to prevent this in _qmenu here 

```
class QModelMenu(QMenu):
    def __init__(self):
        ...
        self.destroyed.connect(self._disconnect)
        # ----------------------

    def _disconnect(self) -> None:
        self._app.menus.menus_changed.disconnect(self._on_registry_changed)
```

but clearly the `_disconnect ` callback connected to the destroyed signal is getting called to late to catch that last `_rebuild` call

**Comment by lucyleeow** [comment]
Ahh okay thanks, this was very enlightening. And yes, now that I know this, I can understand that one would usually just catch the error and leave it at that. Thank you!

**Comment by lucyleeow** [comment]
Thinking about this again, since we added a reference to the `QModel` to the `Window` instance:

```python
        self.sample_menu = build_qmodel_menu(
            MenuId.FILE_SAMPLES, title="samp", parent=self._qt_window
        )
```

I would have thought `window.sample_menu` reference would stick around as long as napari window is open.

**Comment by tlambert03** [comment]
If you mean the Window class in qt_main_window... that is not a QObject.  It's really a prime candidate for the problem I was mentioning:

> The problem occurs when you're holding onto a Python reference to a Qt object that has been destroyed on the C++ side

So that napari python Window object is definitely liable to hold a reference to a QObject (the menus) after the q object has been destroyed on the c++ side (because, for example, the QmainWindow that is the real parent of the menu has been closed).

I'm afraid the napari codebase is filled with stuff like that.  
That's not to oversimplify it (it's definitely tricky stuff to reason about).  But that case at least is a prime candidate for the deleted wrapped object error

**Comment by tlambert03** [comment]
It's a lot of work, but that whole napari window pattern probably needs to be redone.  The idea was good (concept of a non qt Window object that is a napari side object representing a backend qt obejct), but in practice it was implemented in a way where there is very little separation of concerns: it's kinda unclear why the window exists in addition to the _QtMainWindow.  They both have a ton of "qt-ness" about them

**Comment by lucyleeow** [comment]
Ahh okay, I understand the python reference vs c++ object distinction better now. Thanks!

**Comment by tlambert03** [comment]
@lucyleeow, I'm looking a little closer at [your `test_qmenu` branch] to see what's causing this.  To simplify the problem a little bit.  this test is sufficient:

```python
def test_thing(builtins, make_napari_viewer):
    _viewer = make_napari_viewer()
```

and, if I simply comment out your addition to Window, things work again:

```python
        self.sample_menu = build_qmodel_menu(
            MenuId.FILE_SAMPLES, title="samp", parent=self._qt_window
        )
```

I noticed you haven't actually added `self.sample_menu` to anything... what was the goal of adding that line?

**Comment by tlambert03** [comment]
some more details ... ultimately, I think this bug is due to a failure in the disconnection strategy i mentioned above in https://github.com/pyapp-kit/app-model/issues/147#issuecomment-1801076340.

If you add `self.sample_menu.destroyed.connect(lambda: print("DESTROY"))` somewhere, you'll see that the `destroyed`
event IS indeed emitted, but the intended `_disconnect` callback is never getting called (and so `self._app.menus.menus_changed.disconnect(self._on_registry_changed)` is never getting called either).  I think this probably means that the strategy of having a QObject connect its own method to its `destroyed` signal isn't going to work (presumably that callback method *itself* is cleaned up and no longer called).

If you try to outsmart it by using a locally defined function closing on the QObject:

```python
        @self.destroyed.connect
        def _disconnect() -> None:
            self._app.menus.menus_changed.disconnect(self._on_registry_changed)
```

then the _disconnect function *does* get called, but then psygnal has an issue actually executing the disconnection cause it can no longer find the callback to disconnect it:

```pytb
Traceback (most recent call last):
  File "/Users/talley/dev/self/app-model/src/app_model/backends/qt/_qmenu.py", line 58, in _disconnect
    self._app.menus.menus_changed.disconnect(self._on_registry_changed)
  File "src/psygnal/_signal.py", line 827, in disconnect
  File "src/psygnal/_signal.py", line 799, in _slot_index
  File "src/psygnal/_weak_callback.py", line 130, in weak_callback
  File "src/psygnal/_weak_callback.py", line 363, in __init__
  File "src/psygnal/_weak_callback.py", line 190, in __init__
  File "src/psygnal/_weak_callback.py", line 258, in object_key
RuntimeError: wrapped C/C++ object of type QModelSubmenu has been deleted
```

It's possible we could catch and special case that in psygnal itself (to handle the case where essentially all attribute access is no longer permitted on the previously connected callback)... but I need to look into that.

----- 
and one final detail, while I'm looking into this, I think it would also be very reasonable for npe2's PluginContext to catch errors in the dispose method:

```python
class PluginContext:
    def _dispose(self):
        while self._disposables:
            try:
                self._disposables.pop()()
            except Exception as e:
                logger.warn(f'Error while disposing blah blah {e}')
```

**Comment by tlambert03** [comment]
let's continue discussion on this in #157

**Comment by lucyleeow** [comment]
> I noticed you haven't actually added self.sample_menu to anything... what was the goal of adding that line?

Yes. I thought I needed a `QAction` from the submenu for a test, but later realised I did not. Also in the original action manager implementation they made a `QMenu` of the submenu , the app-model implementation did not need it, but I played around with adding it.

**Comment by lucyleeow** [comment]
Silly question related to this thread.

If I did need the `QAction` for a submenu, do I need to build a `QModelMenu` (or `QModelSubMenu`) to access it?

I would think that the `QAction` is created when I build the `QModelMenu` for the parent menu, since the menu builds fine, I just can't figure out how to access it?

**Comment by tlambert03** [comment]
you can get at all of the QAction objects in a QMenu using [`actions()`](https://doc.qt.io/qt-6/qwidget.html#actions):


```python
In [15]: m = QModelMenu('file', app)

In [16]: m
Out[16]: <app_model.backends.qt._qmenu.QModelMenu at 0x13aeea3b0>

In [17]: m.actions()
Out[17]:
[QMenuItemAction(MenuItem(when=None, group='1_loadsave', order=None, command=CommandRule(id='new_file', title='New', category=None, tooltip=None, status_tip='Create a new file', icon=Icon(dark='fa6-solid:file-circle-plus', light='fa6-solid:file-circle-plus'), icon_visible_in_menu=True, enablement=None, short_title=None, toggled=None), alt=None), app='my_app'),
 QMenuItemAction(MenuItem(when=None, group='1_loadsave', order=None, command=CommandRule(id='open_file', title='Open...', category=None, tooltip=None, status_tip='Open an existing file', icon=Icon(dark='fa6-solid:folder-open', light='fa6-solid:folder-open'), icon_visible_in_menu=True, enablement=None, short_title=None, toggled=None), alt=None), app='my_app'),
 QMenuItemAction(MenuItem(when=None, group='1_loadsave', order=None, command=CommandRule(id='save_file', title='Save', category=None, tooltip=None, status_tip='Save the document to disk', icon=Icon(dark='fa6-solid:floppy-disk', light='fa6-solid:floppy-disk'), icon_visible_in_menu=True, enablement=None, short_title=None, toggled=None), alt=None), app='my_app'),
 QMenuItemAction(MenuItem(when=None, group='1_loadsave', order=None, command=CommandRule(id='save_file_as', title='Save As...', category=None, tooltip=None, status_tip='Save the document under a new name', icon=None, icon_visible_in_menu=True, enablement=None, short_title=None, toggled=None), alt=None), app='my_app'),
 <PyQt6.QtGui.QAction at 0x13aeeab00>,
 QMenuItemAction(MenuItem(when=None, group='3_launchexit', order=None, command=CommandRule(id='exit', title='Exit', category=None, tooltip=None, status_tip='Exit the application', icon=None, icon_visible_in_menu=True, enablement=None, short_title=None, toggled=None), alt=None), app='my_app')]
```

**Comment by lucyleeow** [comment]
Ah yes I got it - to get the actions of a submenu you would do `.menu().actions()` on the submenu QAction, which Draga already does here:

https://github.com/napari/napari/blob/eab7661459e70479c7c7d587a36463f3b099b64a/napari/_qt/_qapp_model/_tests/test_file_menu.py#L223-L243

Thanks, sorry for noise!

**Comment by lucyleeow** [comment]
I guess what would be nice is if `findAction` would be able to find actions from submenus  as well, instead of just the parent `QModelMenu`.
