### ISSUE TITLE
DOC Wrong `app` in Qt example in `getting_started`

### ISSUE THREAD

**Issue by lucyleeow** [pyapp-kit/app-model#148]
We create `app` using `QApplication` but then use `my_app` which is meant to be a `app_model.Application`

https://github.com/pyapp-kit/app-model/blob/9e1d527f0b1468d9e3cb83da87d33897ff37c928/docs/getting_started.md?plain=1#L206-L211

**Comment by tlambert03** [comment]
I'm not sure I'm following.  

QModelMainWindow _does_ takes an instance of app_model.Application (not a QAapp).  Did you run this and get an error?

**Comment by lucyleeow** [comment]
Ah nevermind, I got confused between `my_app` and `app`, which I see is used at the end.
