### ISSUE TITLE
No `findAction` in `QModelSubmenu`

### ISSUE THREAD

**Issue by lucyleeow** [pyapp-kit/app-model#153]
There is no `findAction` method for `QModelSubmenu`. Should we be using `QModelMenu` to build submenus? I don't think you `findAction` on a parent `QModelMenu` will work for finding submenu actions.

Thanks

**Comment by tlambert03** [comment]
I'll need a bit more context/example, etc... 
There *is* a `findAction` method on `QModelSubmenu` (by nature of being a subclass of `QModelMenu`.) If that method isn't working as you expect though, let me know where/how and perhaps with a bit of code to demonstrate

**Comment by lucyleeow** [comment]
Oohhh of course that was silly if me. In fact in my example in #147 I should have used `QModelSubmenu` to make a `QModel` of the submenu. Would that have avoided the error?
