### ISSUE TITLE
Support of in-n-out `inject` parameters

### ISSUE THREAD

**Issue by lucyleeow** [pyapp-kit/app-model#169]
I think app-model does not currently support in-n-out `inject` parameters such as:

* `inject` : `on_unresolved_required_args`, `on_unannotated_required_args`, `guess_self`
* `inject_processors`: `first_processor_only`, `raise_exception`

I have no current use of this. Just wanted to confirm and know what the future plans were, for some napari app-model documentation (that I will one day write :grimacing: ).

**Comment by tlambert03** [comment]
Oh, sorry… app-model :) I thought we were in in-n-out here for a moment,  ok let me have a look!

**Comment by tlambert03** [comment]
Ok, the first three parameters can be controlled by setting them direction on the application's store.  For example `app.injection_store.on_unresolved_required_args = 'raise'`.  And correct, app-model doesn't specifically exposure the `first_processor_only` feature yet.  Waiting for a use case

**Comment by tlambert03** [comment]
in napari, you could set those here: 

https://github.com/napari/napari/blob/e6a454eaa3ed8628b1f0c6a3237d9e33e1f96d72/napari/_app_model/_app.py#L30-L33

**Comment by lucyleeow** [comment]
Ah thanks, I did not know.
Feel free to close this or I can amend to only about `first_processor_only`

**Comment by tlambert03** [comment]
I think i'll close it until we have an actual use case.  All users of `app-model` have direct access to the `injection_store` and can do anything with it that they want to.  So, the fact that napari doesn't currently invoke `inject_processors` anywhere is more of a napari-specific topic at this point.  In other words, all of the functionality is already publicly exposed... it's just a matter of how downstream libraries choose to use it.  If you come up with a use case where you feel like you're limited, feel free to reopen.

**Comment by lucyleeow** [comment]
Ah the difference between `register` and `inject` was not clear to me. If you `register` a provider/processor in app_model, all `Action`s callbacks that are typed would automatically use it.

In order to use `inject` parameters, you can set those attributes in `ino.Store` object (e.g., `app.injection_store`)
(Looking at the docs, I don't see the `on_unresolved_required_args` etc attributes documented: https://ino.readthedocs.io/en/latest/reference/#in_n_out.Store, you can just see them when you open "Source code in in_n_out/_store.py")

If you wanted to use `inject_processors` parameters (`first_processor_only` or `raise_exception`), you can use `inject_processors` to decorate the function you want to set the parameter for, e.g.,:

```python
@ino.inject_processors(first_processor_only=True)
def myfun() -> mytype:
    pass
```

**Comment by tlambert03** [comment]
>  I don't see the on_unresolved_required_args etc attributes documented: https://ino.readthedocs.io/en/latest/reference/#in_n_out.Store, you can just see them when you open "Source code in in_n_out/_store.py")

yeah, that could be improved.  We could either add it to the `__init__` params/docstring.  Or expose them via `@property`/`@setter` and give them a docstring there.

**Comment by lucyleeow** [comment]
I forgot to add question marks to my comment. Let me know if I got anything wrong!

**Comment by tlambert03** [comment]
Nope, I think you had it right!
