### ISSUE TITLE
Extend public API: new `progress` attribute in CommandRule, easier access to CommandRule attributes, access to list of all action ids

### ISSUE THREAD

**Issue by Aleshkev** [pyapp-kit/app-model#185]
We (I, @lukaszsmolinski, @Jokilos, @modyf01) are creating [a napari plugin](https://github.com/midi-app-controller/midi-app-controller/) that lets the user execute interface commands on a MIDI controller. This creates some slightly unusual data flow between the app-model library and an external plugin. These are our suggestions for small changes to app-model to facilitate the integration. We consulted them already with @Czaki and he tentatively agreed.

## `progress` attribute

When a command’s main purpose is to interact with a slider in the application, we would like to display the slider’s current value using the MIDI controller’s lighting. We need some method of accessing the current value of the slider associated with the action.
We propose adding an optional ‘progress’ attribute to the CommandRule class that would be analogous to the ‘enablement’ attribute. If the action is used to set the value of some slider, this attribute would return the current state of the slider. Ideally, as a value in the range [0, 1].

## access to `CommandRule.enablement`, `.toggled`, `.progress` without explicit context passing

We need access to attributes like `title`, `enablement`, `palette` and `toggled`. We need `toggled` to know if a controller button corresponding to the command should be lit, `enablement` to make sure the command is executable, `palette` and `title` to determine its visibility in the interface.

CommandRule has these attributes, but as expressions that require app context to evaluate to a value. Also, there is no method of accessing the CommandRule object by id of an action.

We propose adding methods `CommandsRegistry.get_enablement(command_id)`, `.get_title(command_id)`, `.get_palette(command_id)`, and `.get_toggled(command_id)` (and other attributes that CommandRule has, see https://app-model.readthedocs.io/en/latest/reference/types/#app_model.types.CommandRule, like `category` and `tooltip`). Alternatively, these could be methods of the `Application` class.

These methods would do the same thing as `execute_action` but allow interaction with attributes other than `callback`.

## access to a list of all action ids

We need a list of all actions to let the user select any. We propose adding method `CommandsRegistry.get_all_action_ids()` that returns ids of all currently registered actions.

This change is less important than others because there currently exists the `__iter__` method that returns a dictionary with action ids as keys. However, it seems not to be designed for external use as it exposes private data and is absent from the documentation.

**Comment by tlambert03** [comment]
Hi @Aleshkev and thanks for your note.  I think it would be very useful for me if you could provide some pseudocode to explain how you imagine you would use some of these things.  For at least a few of these things I'm not sure that we have the same picture in mind about what app-model is providing & doing, so it would be good to clarify some of those things.

> We need some method of accessing the current value of the slider associated with the action.
>
> We need toggled to know if a controller button corresponding to the command should be lit, enablement to make sure the command is executable, palette and title to determine its visibility in the interface.


The first thing that I think is probably important to point out is: **app-model is largely stateless**.

That is, app-model has no idea as to whether a given command is currently enabled, or toggled, and it holds no values for anything that might be similar to `progress`.  All of that would be found in the **context** managed by the application _using_ `app-model`.  App model just holds declarative information about the commands (functions) available in a program, where a representation of those commands should appear (in menus), when they should be allowed to be executable (enablement), and keys that should trigger those commands (keybindings).  It does not, however, hold the necessary information to tell you whether something is *currently* enabled/visible/toggled, etc. 

>  CommandRule has these attributes, but as expressions that require app context to evaluate to a value. 

 That _is_ the fundamental design. You *must* evaluate one of these expressions using some context (a key value pair that maps the names in the expressions to some current value) to have any idea about their current state.  For your use case, napari would be in charge of that context and you would need to discuss with napari how to access it.  Something like `progress`, for example, is just one of *many* stateful attributes that some data structure might have.  In other words, it sounds like a context key.  Short of offering a `Context` object that has a changed signal to let listeners know that something has changed, app-model really doesn't care too much about what is *in* the context, or what the keys are (i.e. what names are allowed to be used in expressions).  That's all the domain of the app itself (napari).

For more details, see [this overview in the napari docs](https://napari.org/stable/guides/contexts_expressions.html) on contexts, and specifically [this summary section.](https://napari.org/stable/guides/contexts_expressions.html#summary-a-rough-full-picture)

> access to a list of all action ids

using `CommandsRegistry .__iter__` _is_ actually intended for this purpose, or `list(n[0] for n in app.commands)` if you just want the names

> it seems not to be designed for external use as it exposes private data and is absent from the documentation.

was it the fact that the classname for registered command has an underscore?   i can remove that if that caused the confusion.  The id, title, and callback are all public there for a registered command

> Also, there is no method of accessing the CommandRule object by id of an action.

There is, it's `__getitem__`:   `app.commands['command_id']`


---- 

it is true that enablement is not currently stored in the commands registry.  We could potentially look into adding that. but ultimately, enablement is there to inform when *calling* the function is allowed.  That is, it must be provided a context in order to determine whether it's currently enabled.   Since the Commands registry didn't currently have any context-specific functionality, i didn't yet add it.  With understanding of the above details, if you still have a use case for adding enablement to that specific place in the model, please give me a little bit of pseudocode to explain.

Hope that all makes sense!  While I suspect that most of your needs will be met by discussing with napari how context will be managed, i'm definitely open to making modifications to the storage of basic info of the app-model types, provided we have a compelling use case.

cheers,

**Comment by tlambert03** [comment]
my apologies, i didn't mean to close this.  that was a mistake

**Comment by Aleshkev** [comment]
Thanks for the detailed explanation.

I agree with the statelesness of app-model, I didn't see it that way because the backends have lots of state but I think I kind of get the point. We'll get the context from the napari's side of things.

## `__iter__` (solved)

> using CommandsRegistry .__iter__ is actually intended for this purpose, or list(n[0] for n in app.commands) if you just want the names
Thanks for the clarification. We weren't sure about using this mainly because it is absent from the documentation. But this solves the issue.

## Access to attributes (not important anymore)

> > Also, there is no method of accessing the CommandRule object by id of an action.
>
> There is, it's `__getitem__`: `app.commands['command_id']`

We are interested in access to attributes `enablement`, `toggled` etc. while `__getitem__` returns a `_RegisteredCommand` with only has `id`, `callback`, and `title`. We need `CommandRule` (or `Action` or other descendants). 

To provide pseudocode, we would like to do something simple like that:

```py
toggled = app.is_command_toggled(action_id)
our_button.set_light("on" if toggled else "off")
```
Or some equivalent, for example (assuming that we have to provide the context ourselves):
```py
toggled = app.get_toggled(action_id).eval(context)
our_button.set_light("on" if toggled else "off")
```
Or we could receive the `Action` object:
```py
toggled = app.get_action_object(action_id).toggled.eval(context)
our_button.set_light("on" if toggled else "off")
```
I understand that these are currently not stored anywhere in the CommandRegistry, that's why I suggested they might need to be in `Application`. However, I see now that the CommandRule objects are actually stored inside MenuRegistry (more precisely, `MenuItem.command`). So some code liek the following solves our issue:

```py
toggled = list(list(app.menus)[3][1].keys())[...].command.toggled.eval(context)
our_button.set_light("on" if toggled else "off")
```

I feel the API could be modified to make this simpler and more obvious but it's not important since we can get our code working without any changes.

## `progress` attribute

Therefore, the only issue that remains is the question of `progress` attribute.

To explain again, the `progress` attribute would be just like `toggled` but returning a float instead of a bool. The application (napari) would be free to define the float value of an action where it makes sense, for example an action that sets layer opacity would return the current opacity. I believe this is perfectly analogous to the `toggled` attribute, I can even imagine this being displayed in regular app menus.

> Something like progress, for example, is just one of _many_ stateful attributes that some data structure might have
This is true but I feel like this is directly related to how an action is displayed and therefore belongs in the same category as `toggled` and `enablement`. If they are included, so should be `progress`.

**Comment by Aleshkev** [comment]
Thanks for the detailed explanation.

I agree with the statelesness of app-model, I didn't see it that way because the backends have lots of state but I think I get the point. We'll get the context from the napari's side of things.

## `__iter__` (solved)

> using CommandsRegistry .__iter__ is actually intended for this purpose, or list(n[0] for n in app.commands) if you just want the names

Thanks for the clarification. We weren't sure about using this mainly because it is absent from the documentation. But this solves the issue.

## Access to attributes (solved)

We found that the data we need is already available publicly but in MenusRegistry instead of CommandsRegistry. So that's solved then.

## `progress` attribute

Therefore, the only issue that remains is the question of `progress` attribute.

To explain again, the `progress` attribute would be just like `toggled` but returning a float instead of a bool. The application (napari) would be free to define the float value of an action where it makes sense, for example an action that sets layer opacity would return the current opacity. I believe this is perfectly analogous to the `toggled` attribute, I can even imagine this being displayed in regular app menus.

> Something like progress, for example, is just one of _many_ stateful attributes that some data structure might have

This is true but I feel like this is directly related to how an action is displayed and therefore belongs in the same category as `toggled` and `enablement`. If they are included, so should be `progress`.

**Comment by tlambert03** [comment]
> I didn't see it that way because the backends have lots of state but I think I get the point.

yeah, they have the state of things that are actually in the menus and such, but beyond that, for things like enabled/toggled, they *also* actually require the consuming application to provide a context.  They mostly depend on the `update_from_context` methods, which aren't actually called internally anywhere (except for recursive self-calls):

https://github.com/pyapp-kit/app-model/blob/e8fb729c450ee7a9bcda4c21997912d5f3aeb240/src/app_model/backends/qt/_qmenu.py#L73-L81

Those are meant to be called be the actual app program, with the context (that the app is managing).  For example, napari does it here, among other places:  https://github.com/napari/napari/blob/f9709d8a9eed8f1ab41596d71b7b29ee4390f64e/napari/_qt/qt_main_window.py#L811

> To explain again, the progress attribute would be just like toggled but returning a float instead of a bool. The application (napari) would be free to define the float value of an action where it makes sense, for example an action that sets layer opacity would return the current opacity.

perhaps it's just semantics, but I don't see app-model's `toggled` concept as "returning a bool".  It's not a function, it's an expression that evaluates to a bool.  Just like `x > 10` is not a bool, without knowing what `x` is.  Similarly I'm not sure what it means to "define the float value of an action".  Actions don't have values, they do things when triggered, and have places in the GUI where they can be triggered (like menus, toolbars, and keybindings).  Progress (and any other value-like thing) feels like data, just like "number of current layers", or any of the other context keys mentioned on the napari docs page above.

> This is true but I feel like this is directly related to how an action is displayed and therefore belongs in the same category as toggled and enablement. If they are included, so should be progress.

I'm not sure I agree on that.  _All_ actions, be they represented in menus, or as toolbars, have the possibility to be toggled/enabled/visible.  These are fundamental enough to the concept of an "action" in any GUI that Qt also models its actions (QAction) as having `enabled`, `checked`, and `visible` states (https://doc.qt.io/qt-6/qaction.html#properties).  It does not, however, have a `progress` property or anything like it on `QAction` and I don't think it would be safe to say that the concept of progress would make sense for all actions.  So, i don't agree that the inclusion of `toggled` and `enablement` (which all GUI frameworks generally represent in their Action-like class) means that `progress` should be.  It would appear that Qt also hasn't seen a need to include that specific of a data-point at this level of abstraction either.

It's unclear exactly what app-model would *do* with that attribute: establishing a whole API for accepting feedback from a command about it's progress state also feels outside of the scope of this project.

Of course, that's not to say that I can't absolutely imagine that napari will want to indicate the progress of various things.  but i'm afraid I still see it as something that would fit better into napari's progress API https://napari.org/stable/api/napari.utils.progress.html  ... or a napari context object.  For now at least.  

If you come closer to a place where it's very clear what app-model itself would actually do with `progress` (outside of simply being a container for some internally unused value that some other library would need to make sense of), please feel free to open an issue with a little bit of concrete code showing what changes you would make to app model and how downstream libraries would use it.   thanks

**Comment by Czaki** [comment]
> perhaps it's just semantics, but I don't see app-model's `toggled` concept as "returning a bool". It's not a function, it's an expression that evaluates to a bool. Just like `x > 10` is not a bool, without knowing what `x` is. Similarly I'm not sure what it means to "define the float value of an action". Actions don't have values, they do things when triggered, and have places in the GUI where they can be triggered (like menus, toolbars, and keybindings). Progress (and any other value-like thing) feels like data, just like "number of current layers", or any of the other context keys mentioned on the napari docs page above.

As I understand, `toggled` was added to allow update interface with feedback information about the current state of application without need to inspect the real state. Something like `progress` is a natural extension for any state that is not binary. 

Currently, one could implement toggle menu position or interface checkbox using only Actions, but it is impossible to implement things like an opacity slider, or gamma slider. 
Maybe this should not be a float, but information about range and current value. Maybe there should be RangeAction in place of Action.

As I understand, Actions are designed to provide a stable interface for inner elements, but also plugins/extensions. So for me, this is the natural direction of development.

**Comment by tlambert03** [comment]
> toggled was added to allow update interface with feedback information about the current state of application without need to inspect the real state. Something like progress is a natural extension for any state that is not binary.

toggled was added to inform the [`QAction.checked` property](https://doc.qt.io/qt-6/qaction.html#checked-prop).

> Currently, one could implement toggle menu position or interface checkbox using only Actions, but it is impossible to implement things like an opacity slider, or gamma slider.

I never intended app-model to be a complete declarative description of all the state in an application, and I think it would be a mistake to do that sort of thing via contexts and expressions.  That sort of stuff _does_, however, sit nicely in the scope of magicgui.  For example, all of the Layer controls would be nicely generated by the new pydantic-to-magicgui-widget functionality.  App-model is not a replacement for magicgui and is not intended to generate complex QWidgets such as sliders, progressbars, checkboxes.  The expression/context arrangement isn't intended performancewise to back rapidly changing float values like sliders and progress bars. 

As mentioned before, this is all very abstract at the moment.  And in the abstract, I'm just not seeing it.  I'm not seeing how it fits into QActions, and if you're proposing an extension of the scope to build complete GUIs, I'm not seeing how this isn't better suited to magicgui. 

If you would like to elaborate on your proposal, to show exactly what you would have app-model do with full-blown state management for all types of widgets (like sliders and progress bars), feel free to do so.
