### ISSUE TITLE
feat: include action current keybinding as part of its tooltip

### ISSUE THREAD

**Issue by dalthviz** [pyapp-kit/app-model#216]
### Description

When an action has a keybinding set it could be nice to be able to see it as part of the action's tooltip. So, for example, over napari,you can see tooltips formated in the following way:

![imagen](https://github.com/user-attachments/assets/593a79ad-74cd-4a53-9fc4-3dc121dc2ab4)

This is part of the elements that started to be discussed over an exploration to use `QModelToolBar`s for buttons over napari. For more details on that you can see https://github.com/napari/napari/pull/7133

**Comment by tlambert03** [comment]
find by me 👍
