### ISSUE TITLE
Tests crash on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [pyapp-kit/app-model#228]
[log](https://freebsd.org/~yuri/py-app-model-0.3.1-tests.log)

* app-model version: 0.3.1
* Python version: 3.11
* Operating System: FreeBSD 14.1

### Description
```
tests/test_qt/test_demos.py::test_qapp[qapplication.py] Fatal Python error: Aborted

Current thread 0x00003649d9012000 (most recent call first):
  File "/usr/local/lib/python3.11/site-packages/pytestqt/plugin.py", line 66 in qapp
  File "/usr/local/lib/python3.11/site-packages/_pytest/fixtures.py", line 913 in call_fixture_func
```

**Comment by tlambert03** [comment]
thanks @yurivict, is it safe to assume that this is for bundling in a freebsd package manager?  or were these tests you ran locally?

I admit, I don't have a lot of experience in how freebsd might differ from ubuntu when it comes to gui-related & Qt issues.  Is this something you've been running in the past and has only started failing?  Or was this the first time you tried running these tests on freebsd?

**Comment by yurivict** [comment]
I've ran the tests locally in from the FreeBSD port directory.

**Comment by tlambert03** [comment]
Ok.  Well you might be the first user to try this with FreeBSD.  I have zero experience with GUI frameworks in FreeBSD, so i would probably need your help/participation to try to get to the bottom of this one.  Let me know if that's something you're interested in doing

**Comment by yurivict** [comment]
I can try to help.

**Comment by yurivict** [comment]
This looks like some PyTest arguments related error because tests in some other similar ports crash the same way.
All tests pass when run separately with a simple pytest command.

Sorry for this disturbance.
