### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by davidbrochart** [pyapp-kit/app-model#87]
It looks like `app-model` doesn't support running in an event loop? For instance, commands can only be [executed asynchronously through threads](https://github.com/pyapp-kit/app-model/blob/d87f77ac8c4d78361b8a302a33c7f93d42f63bb2/src/app_model/registries/_commands_reg.py#L195-L197).
Do you think it could support async GUI backends? I'm thinking about [Textual](https://textual.textualize.io) in particular.

**Comment by tlambert03** [comment]
yeah, the motivating use case for app-model was napari (with a Qt event loop).  But I definitely tried to make it backend agnostic, and would love to support asyncio runtimes as well.  I don't have a ton of experience with asyncio (though I'd like to know more), so if you have thoughts on what the API should look like for registering/executing awaitable commands, or even just a simple example of how you'd _like_ it all to work, that would be great.

**Comment by tlambert03** [comment]
would be as easy as simply calling and returning the coroutine object if it's a coroutine function? ( adding `typing.Awaitable` to the return type 

```python
    def execute_command(
        self,
        id: str,
        *args: Any,
        **kwargs: Any,
    ) -> Future | Awaitable:
        ...
        if iscoroutinefunction(cmd):
            return cmd(*args, **kwargs)
```

that appears to work in ipython with `await reg.execute_command('some_id')`

**Comment by davidbrochart** [comment]
Maybe it's as simple as that, yes. If app-model works with an event-loop based framework like Qt, then it should also work with a framework like Textual.
I'll try to use it for [jpterm](https://github.com/davidbrochart/jpterm). It would be awesome if we could seamlessly switch backends.

**Comment by tlambert03** [comment]
closing, since i think app-model already supports async (though if anyone finds a good counter-example, please feel free to note it here)
