### ISSUE TITLE
Error instantiating QModelMenu with PySide6 6.5.0

### ISSUE THREAD

**Issue by aganders3** [pyapp-kit/app-model#93]
* app-model version: `main` (`0.1.2`)
* Python version: `3.10.10`
* Operating System: macOS 13.3

### Description
There is a problem instantiating the `QModelMenu` with PySide 6.5.0. It looks like multiple inheritance gets a bit trickier here as now QWidget is effectively calling `super().__init__`? This feels like a pretty big change so perhaps it should be reported on the Qt bug tracker.

Try this demo script to see what I mean:

```python
# qwidget_demo.py
from PySide6.QtCore import QObject
from PySide6.QtWidgets import QApplication, QWidget

app = QApplication([])


class A(QObject):
    def __init__(self, *args, **kwargs):
        print("A.__init__", args, kwargs)


class B(QWidget, A):
    def __init__(self, *args, **kwargs):
        QWidget.__init__(self, *args, **kwargs)
        print("B.__init__", args, kwargs)


print("instantiating A")
A()

print("instantiating B")
B()
```

#### output with PySide 6.4.2
```
❯ python qwidget_demo.py 
instantiating A
A.__init__ () {}
instantiating B
B.__init__ () {}
```
#### output with PySide 6.5.0
```
❯ python qwidget_demo.py 
instantiating A
A.__init__ () {}
instantiating B
A.__init__ () {}
B.__init__ () {}
```

### What I Did
Create a virtual environment with the newly released PySide6 v6.5.0:
```
% python -m venv venv
% source venv/bin/activate
% pip install pyside6==6.5.0
% pip install -e '.[qt,test,test-qt]'
% pytest
```

Tests are failing for `QMenu` with this rather confusing output:

```
self = <[RuntimeError("'__init__' method of object's base class (QModelMenu) not called.") raised in repr()] QModelMenu object at 0x12e46ae00>, menu_id = 'help'
app = Application('complete_test_app'), title = None, parent = None

    def __init__(
        self,
        menu_id: str,
        app: Union[str, Application],
        title: Optional[str] = None,
        parent: Optional[QWidget] = None,
    ):
>       QMenu.__init__(self, parent)
E       TypeError: _MenuMixin.__init__() missing 1 required positional argument: 'app'

src/app_model/backends/qt/_qmenu.py:144: TypeError
```

### Possible solution?

I'm not sure what the best solution is here - I don't have a ton of experience with multiple inheritance or mixins. One thing that seems to work is to give `_MenuMixin` a dummy `__init__` like this, but it doesn't necessarily feel like the right way to do it:

```diff
--- a/src/app_model/backends/qt/_qmenu.py
+++ b/src/app_model/backends/qt/_qmenu.py
@@ -44,7 +44,10 @@ class _MenuMixin(QObject):
     _app: Application
     _menu_id: str
 
-    def __init__(
+    def __init__(self, *args, **kwargs):
+        pass
+
+    def _init_mixin(
         self,
         menu_id: str,
         app: Union[str, Application],
@@ -141,8 +144,9 @@ class QModelMenu(QMenu, _MenuMixin):
         title: Optional[str] = None,
         parent: Optional[QWidget] = None,
     ):
+        print(QModelMenu.__mro__)
         QMenu.__init__(self, parent)
-        _MenuMixin.__init__(self, menu_id, app)
+        self._init_mixin(menu_id, app)
         if title is not None:
             self.setTitle(title)
         self.aboutToShow.connect(self._on_about_to_show)
@@ -217,7 +221,7 @@ class QModelToolBar(QToolBar, _MenuMixin):
     ) -> None:
         self._exclude = exclude
         QToolBar.__init__(self, parent)
-        _MenuMixin.__init__(self, menu_id, app)
+        self._init_mixin(menu_id, app)
         if title is not None:
             self.setWindowTitle(title)
```

**Comment by Czaki** [comment]
PySide started properly supports multiple inheritances

**Comment by aganders3** [comment]
Ah and according to the [qt issue](https://bugreports.qt.io/plugins/servlet/mobile#issue/PYSIDE-1564) not a problem in PyQt. So maybe the fix should be in qtpy?

Anyway I'm glad you're already aware of it!

**Comment by Czaki** [comment]
But PySide6 is proper behavior in the context of Python. If you inherit from A, then A initialization (`__init__`) needs to be called. Otherwise, what do you expect to happen when you call the method from A that requires a field initialized in A?

**Comment by tlambert03** [comment]
@aganders3 observation is a good one, look at the behavior in his original post for 6.5.0

`A.__init__ () {}` should NOT be called when instantiating B in his example.  Something has changed and pyside is doing something unusual

**Comment by Czaki** [comment]
I hope that this example allows understanding what happens:

```
class A:
    def __init__(self):
        print("initiating A")


class B:
    def __init__(self):
        super().__init__()
        print("initiating B")


class C:
    def __init__(self):
        super().__init__()
        print("initiating C")


class D(A, C):
    def __init__(self):
        A.__init__(self)
        print("initiating D")


class E(B, C):
    def __init__(self):
        B.__init__(self)
        print("initiating E")


D()
print("#" * 20)
E()
```

And class `B` behaviour is more proper for python.

**Comment by tlambert03** [comment]
I think you might be missing the point.  It's not about what is proper for python, and it's also not about using super.

Note that initiating C does NOT get printed in your example when you instantiate D, but A does get initiated in his original example when he instantiates B... but only in pyside 6.5

Pyside is doing something weird

**Comment by tlambert03** [comment]
Oh is your point just that they've presumably added a super call somewhere in QObject that wasn't there before?

**Comment by Czaki** [comment]
Yes. I mean that PySide6 changes the constructor's behavior to a more Pythonic one to allow proper multiple inheritances. 

Of course, this change may breaks some code (as we see), but calling all constructors of superclasses is expected behavior,

**Comment by tlambert03** [comment]
Ok, yeah I agree, they just changed their constructor.  Whether it's expected or not, it's a potentially breaking change. 

It's fine, I didn't ever like the mixin design anyway, so the PR removes it.

**Comment by aganders3** [comment]
Thanks for the discussion. I believe you're correct @Czaki that this is more Pythonic but regardless it's a breaking change.

My understanding is way to make this work involves designing all involved classes with multiple inheritance in mind. It's pretty easy to reason about with the above examples where there are no inputs to `__init__`, but otherwise I think you need to use generic `*args` and `**kwargs` in `__init__` and pass unused args to `super().__init__(*args, **kwargs)`). IMO this quickly becomes difficult to read. The classes in question not being pure Python you can inspect makes it even harder. I tried some of these things and ended up with segmentation faults 🙁. 

All this to say the solution proposed in #95 looks good to me 😄
